server:
  port: 9001
feign:
  hystrix:
    enabled: true
#hystrix超时时间配置 （如果不配置的话默认是1000毫秒超时）
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 9000

management:
  endpoints:
    web:
      exposure:
        include: '*'