server:
  port: 9000
spring:
  application:
    name: spring-cloud-producer
  zipkin:
    base-url: http://localhost:8092
    sender:
      type: web

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/



